type Libdoc = {
  specversion: number;
  name: string;
  doc: string;
  version: string;
  generated: string;
  type: string;
  scope: string;
  docFormat: string;
  source: string;
  lineno: number;
  tags: Array<any>;
  inits: Array<any>;
  keywords: Array<any>;
  typedocs: Array<any>;
  selectedTag: string;
};

const DATA: Libdoc = {
  specversion: 3,
  name: "Telnet",
  doc: '<p>A library providing communication over Telnet connections.</p>\n<p><code>Telnet</code> is Robot Framework\'s standard library that makes it possible to connect to Telnet servers and execute commands on the opened connections.</p>\n<h3 id="Table of contents">Table of contents</h3>\n<ul>\n<li><a href="#Connections" class="name">Connections</a></li>\n<li><a href="#Writing%20and%20reading" class="name">Writing and reading</a></li>\n<li><a href="#Configuration" class="name">Configuration</a></li>\n<li><a href="#Terminal%20emulation" class="name">Terminal emulation</a></li>\n<li><a href="#Logging" class="name">Logging</a></li>\n<li><a href="#Time%20string%20format" class="name">Time string format</a></li>\n<li><a href="#Boolean%20arguments" class="name">Boolean arguments</a></li>\n<li><a href="#Importing" class="name">Importing</a></li>\n<li><a href="#Keywords" class="name">Keywords</a></li>\n</ul>\n<h2 id="Connections">Connections</h2>\n<p>The first step of using <code>Telnet</code> is opening a connection with <a href="#Open%20Connection" class="name">Open Connection</a> keyword. Typically the next step is logging in with <a href="#Login" class="name">Login</a> keyword, and in the end the opened connection can be closed with <a href="#Close%20Connection" class="name">Close Connection</a>.</p>\n<p>It is possible to open multiple connections and switch the active one using <a href="#Switch%20Connection" class="name">Switch Connection</a>. <a href="#Close%20All%20Connections" class="name">Close All Connections</a> can be used to close all the connections, which is especially useful in suite teardowns to guarantee that all connections are always closed.</p>\n<h2 id="Writing and reading">Writing and reading</h2>\n<p>After opening a connection and possibly logging in, commands can be executed or text written to the connection for other reasons using <a href="#Write" class="name">Write</a> and <a href="#Write%20Bare" class="name">Write Bare</a> keywords. The main difference between these two is that the former adds a <a href="#Configuration">configurable newline</a> after the text automatically.</p>\n<p>After writing something to the connection, the resulting output can be read using <a href="#Read" class="name">Read</a>, <a href="#Read%20Until" class="name">Read Until</a>, <a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a>, and <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a> keywords. Which one to use depends on the context, but the latest one is often the most convenient.</p>\n<p>As a convenience when running a command, it is possible to use <a href="#Execute%20Command" class="name">Execute Command</a> that simply uses <a href="#Write" class="name">Write</a> and <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a> internally. <a href="#Write%20Until%20Expected%20Output" class="name">Write Until Expected Output</a> is useful if you need to wait until writing something produces a desired output.</p>\n<p>Written and read text is automatically encoded/decoded using a <a href="#Configuration">configured encoding</a>.</p>\n<p>The ANSI escape codes, like cursor movement and color codes, are normally returned as part of the read operation. If an escape code occurs in middle of a search pattern it may also prevent finding the searched string. <a href="#Terminal%20emulation" class="name">Terminal emulation</a> can be used to process these escape codes as they would be if a real terminal would be in use.</p>\n<h2 id="Configuration">Configuration</h2>\n<p>Many aspects related the connections can be easily configured either globally or per connection basis. Global configuration is done when <a href="#Importing">library is imported</a>, and these values can be overridden per connection by <a href="#Open%20Connection" class="name">Open Connection</a> or with setting specific keywords <a href="#Set%20Timeout" class="name">Set Timeout</a>, <a href="#Set%20Newline" class="name">Set Newline</a>, <a href="#Set%20Prompt" class="name">Set Prompt</a>, <a href="#Set%20Encoding" class="name">Set Encoding</a>, <a href="#Set%20Default%20Log%20Level" class="name">Set Default Log Level</a> and <a href="#Set%20Telnetlib%20Log%20Level" class="name">Set Telnetlib Log Level</a>.</p>\n<p>Values of <code>environ_user</code>, <code>window_size</code>, <code>terminal_emulation</code>, and <code>terminal_type</code> can not be changed after opening the connection.</p>\n<h3 id="Timeout">Timeout</h3>\n<p>Timeout defines how long is the maximum time to wait when reading output. It is used internally by <a href="#Read%20Until" class="name">Read Until</a>, <a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a>, <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a>, and <a href="#Login" class="name">Login</a> keywords. The default value is 3 seconds.</p>\n<h3 id="Connection Timeout">Connection Timeout</h3>\n<p>Connection Timeout defines how long is the maximum time to wait when opening the telnet connection. It is used internally by <a href="#Open%20Connection" class="name">Open Connection</a>. The default value is the system global default timeout.</p>\n<h3 id="Newline">Newline</h3>\n<p>Newline defines which line separator <a href="#Write" class="name">Write</a> keyword should use. The default value is <code>CRLF</code> that is typically used by Telnet connections.</p>\n<p>Newline can be given either in escaped format using <code>\\n</code> and <code>\\r</code> or with special <code>LF</code> and <code>CR</code> syntax.</p>\n<p>Examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Set%20Newline" class="name">Set Newline</a></td>\n<td>\\n</td>\n</tr>\n<tr>\n<td><a href="#Set%20Newline" class="name">Set Newline</a></td>\n<td>CRLF</td>\n</tr>\n</table>\n<h3 id="Prompt">Prompt</h3>\n<p>Often the easiest way to read the output of a command is reading all the output until the next prompt with <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a>. It also makes it easier, and faster, to verify did <a href="#Login" class="name">Login</a> succeed.</p>\n<p>Prompt can be specified either as a normal string or a regular expression. The latter is especially useful if the prompt changes as a result of the executed commands. Prompt can be set to be a regular expression by giving <code>prompt_is_regexp</code> argument a true value (see <a href="#Boolean%20arguments" class="name">Boolean arguments</a>).</p>\n<p>Examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>prompt=$</td>\n</tr>\n<tr>\n<td><a href="#Set%20Prompt" class="name">Set Prompt</a></td>\n<td>(&gt; |# )</td>\n<td>prompt_is_regexp=true</td>\n</tr>\n</table>\n<h3 id="Encoding">Encoding</h3>\n<p>To ease handling text containing non-ASCII characters, all written text is encoded and read text decoded by default. The default encoding is UTF-8 that works also with ASCII. Encoding can be disabled by using a special encoding value <code>NONE</code>. This is mainly useful if you need to get the bytes received from the connection as-is.</p>\n<p>Notice that when writing to the connection, only Unicode strings are encoded using the defined encoding. Byte strings are expected to be already encoded correctly. Notice also that normal text in data is passed to the library as Unicode and you need to use variables to use bytes.</p>\n<p>It is also possible to configure the error handler to use if encoding or decoding characters fails. Accepted values are the same that encode/decode functions in Python strings accept. In practice the following values are the most useful:</p>\n<ul>\n<li><code>ignore</code>: ignore characters that cannot be encoded (default)</li>\n<li><code>strict</code>: fail if characters cannot be encoded</li>\n<li><code>replace</code>: replace characters that cannot be encoded with a replacement character</li>\n</ul>\n<p>Examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>encoding=Latin1</td>\n<td>encoding_errors=strict</td>\n</tr>\n<tr>\n<td><a href="#Set%20Encoding" class="name">Set Encoding</a></td>\n<td>ISO-8859-15</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Set%20Encoding" class="name">Set Encoding</a></td>\n<td>errors=ignore</td>\n<td></td>\n<td></td>\n</tr>\n</table>\n<h3 id="Default log level">Default log level</h3>\n<p>Default log level specifies the log level keywords use for <a href="#Logging" class="name">logging</a> unless they are given an explicit log level. The default value is <code>INFO</code>, and changing it, for example, to <code>DEBUG</code> can be a good idea if there is lot of unnecessary output that makes log files big.</p>\n<h3 id="Terminal type">Terminal type</h3>\n<p>By default the Telnet library does not negotiate any specific terminal type with the server. If a specific terminal type, for example <code>vt100</code>, is desired, the terminal type can be configured in <a href="#Importing" class="name">importing</a> and with <a href="#Open%20Connection" class="name">Open Connection</a>.</p>\n<h3 id="Window size">Window size</h3>\n<p>Window size for negotiation with the server can be configured when <a href="#Importing" class="name">importing</a> the library and with <a href="#Open%20Connection" class="name">Open Connection</a>.</p>\n<h3 id="USER environment variable">USER environment variable</h3>\n<p>Telnet protocol allows the <code>USER</code> environment variable to be sent when connecting to the server. On some servers it may happen that there is no login prompt, and on those cases this configuration option will allow still to define the desired username. The option <code>environ_user</code> can be used in <a href="#Importing" class="name">importing</a> and with <a href="#Open%20Connection" class="name">Open Connection</a>.</p>\n<h2 id="Terminal emulation">Terminal emulation</h2>\n<p>Telnet library supports terminal emulation with <a href="http://pyte.readthedocs.io">Pyte</a>. Terminal emulation will process the output in a virtual screen. This means that ANSI escape codes, like cursor movements, and also control characters, like carriage returns and backspaces, have the same effect on the result as they would have on a normal terminal screen. For example the sequence <code>acdc\\x1b[3Dbba</code> will result in output <code>abba</code>.</p>\n<p>Terminal emulation is taken into use by giving <code>terminal_emulation</code> argument a true value (see <a href="#Boolean%20arguments" class="name">Boolean arguments</a>) either in the library initialization or with <a href="#Open%20Connection" class="name">Open Connection</a>.</p>\n<p>As Pyte approximates vt-style terminal, you may also want to set the terminal type as <code>vt100</code>. We also recommend that you increase the window size, as the terminal emulation will break all lines that are longer than the window row length.</p>\n<p>When terminal emulation is used, the <a href="#Newline" class="name">newline</a> and <a href="#Encoding" class="name">encoding</a> can not be changed anymore after opening the connection.</p>\n<p>Examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=True</td>\n<td>terminal_type=vt100</td>\n<td>window_size=400x100</td>\n</tr>\n</table>\n<p>As a prerequisite for using terminal emulation, you need to have Pyte installed. Due to backwards incompatible changes in Pyte, different Robot Framework versions support different Pyte versions:</p>\n<ul>\n<li>Pyte 0.6 and newer are supported by Robot Framework 3.0.3. Latest Pyte version can be installed (or upgraded) with <code>pip install --upgrade pyte</code>.</li>\n<li>Pyte 0.5.2 and older are supported by Robot Framework 3.0.2 and earlier. Pyte 0.5.2 can be installed with <code>pip install pyte==0.5.2</code>.</li>\n</ul>\n<h2 id="Logging">Logging</h2>\n<p>All keywords that read something log the output. These keywords take the log level to use as an optional argument, and if no log level is specified they use the <a href="#Configuration">configured</a> default value.</p>\n<p>The valid log levels to use are <code>TRACE</code>, <code>DEBUG</code>, <code>INFO</code> (default), and <code>WARN</code>. Levels below <code>INFO</code> are not shown in log files by default whereas warnings are shown more prominently.</p>\n<p>The <a href="http://docs.python.org/library/telnetlib.html">telnetlib module</a> used by this library has a custom logging system for logging content it sends and receives. By default these messages are written using <code>TRACE</code> level, but the level is configurable with the <code>telnetlib_log_level</code> option either in the library initialization, to the <a href="#Open%20Connection" class="name">Open Connection</a> or by using the <a href="#Set%20Telnetlib%20Log%20Level" class="name">Set Telnetlib Log Level</a> keyword to the active connection. Special level <code>NONE</code> con be used to disable the logging altogether.</p>\n<h2 id="Time string format">Time string format</h2>\n<p>Timeouts and other times used must be given as a time string using format like <code>15 seconds</code> or <code>1min 10s</code>. If the timeout is given as just a number, for example, <code>10</code> or <code>1.5</code>, it is considered to be seconds. The time string format is described in more detail in an appendix of <a href="http://robotframework.org/robotframework/#user-guide">Robot Framework User Guide</a>.</p>\n<h2 id="Boolean arguments">Boolean arguments</h2>\n<p>Some keywords accept arguments that are handled as Boolean values true or false. If such an argument is given as a string, it is considered false if it is an empty string or equal to <code>FALSE</code>, <code>NONE</code>, <code>NO</code>, <code>OFF</code> or <code>0</code>, case-insensitively. Other strings are considered true regardless their value, and other argument types are tested using the same <a href="http://docs.python.org/library/stdtypes.html#truth">rules as in Python</a>.</p>\n<p>True examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=True</td>\n<td># Strings are generally true.</td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=yes</td>\n<td># Same as the above.</td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=${TRUE}</td>\n<td># Python <code>True</code> is true.</td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=${42}</td>\n<td># Numbers other than 0 are true.</td>\n</tr>\n</table>\n<p>False examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=False</td>\n<td># String <code>false</code> is false.</td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=no</td>\n<td># Also string <code>no</code> is false.</td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=${EMPTY}</td>\n<td># Empty string is false.</td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>lolcathost</td>\n<td>terminal_emulation=${FALSE}</td>\n<td># Python <code>False</code> is false.</td>\n</tr>\n</table>\n<p>Considering string <code>NONE</code> false is new in Robot Framework 3.0.3 and considering also <code>OFF</code> and <code>0</code> false is new in Robot Framework 3.1.</p>',
  version: "7.0.1.dev1",
  generated: "2024-04-08T08:16:18+00:00",
  type: "LIBRARY",
  scope: "SUITE",
  docFormat: "HTML",
  source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
  lineno: 36,
  tags: [],
  inits: [
    {
      name: "__init__",
      args: [
        {
          name: "timeout",
          type: null,
          defaultValue: "3 seconds",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "timeout=3 seconds",
        },
        {
          name: "newline",
          type: null,
          defaultValue: "CRLF",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "newline=CRLF",
        },
        {
          name: "prompt",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "prompt=None",
        },
        {
          name: "prompt_is_regexp",
          type: null,
          defaultValue: "False",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "prompt_is_regexp=False",
        },
        {
          name: "encoding",
          type: null,
          defaultValue: "UTF-8",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "encoding=UTF-8",
        },
        {
          name: "encoding_errors",
          type: null,
          defaultValue: "ignore",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "encoding_errors=ignore",
        },
        {
          name: "default_log_level",
          type: null,
          defaultValue: "INFO",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "default_log_level=INFO",
        },
        {
          name: "window_size",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "window_size=None",
        },
        {
          name: "environ_user",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "environ_user=None",
        },
        {
          name: "terminal_emulation",
          type: null,
          defaultValue: "False",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "terminal_emulation=False",
        },
        {
          name: "terminal_type",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "terminal_type=None",
        },
        {
          name: "telnetlib_log_level",
          type: null,
          defaultValue: "TRACE",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "telnetlib_log_level=TRACE",
        },
        {
          name: "connection_timeout",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "connection_timeout=None",
        },
      ],
      returnType: null,
      doc: '<p>Telnet library can be imported with optional configuration parameters.</p>\n<p>Configuration parameters are used as default values when new connections are opened with <a href="#Open%20Connection" class="name">Open Connection</a> keyword. They can also be overridden after opening the connection using the <span class="name">Set ...</span> <a href="#Keywords" class="name">keywords</a>. See these keywords as well as <a href="#Configuration" class="name">Configuration</a>, <a href="#Terminal%20emulation" class="name">Terminal emulation</a> and <a href="#Logging" class="name">Logging</a> sections above for more information about these parameters and their possible values.</p>\n<p>See <a href="#Time%20string%20format" class="name">Time string format</a> and <a href="#Boolean%20arguments" class="name">Boolean arguments</a> sections for information about using arguments accepting times and Boolean values, respectively.</p>\n<p>Examples (use only one of these):</p>\n<table border="1">\n<tr>\n<th>Setting</th>\n<th>Value</th>\n<th>Value</th>\n<th>Value</th>\n<th>Value</th>\n<th>Comment</th>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td></td>\n<td></td>\n<td></td>\n<td># default values</td>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td>5 seconds</td>\n<td></td>\n<td></td>\n<td># set only timeout</td>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td>newline=LF</td>\n<td>encoding=ISO-8859-1</td>\n<td></td>\n<td># set newline and encoding using named arguments</td>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td>prompt=$</td>\n<td></td>\n<td></td>\n<td># set prompt</td>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td>prompt=(&gt; |# )</td>\n<td>prompt_is_regexp=yes</td>\n<td></td>\n<td># set prompt as a regular expression</td>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td>terminal_emulation=True</td>\n<td>terminal_type=vt100</td>\n<td>window_size=400x100</td>\n<td># use terminal emulation with defined window size and terminal type</td>\n</tr>\n<tr>\n<td>Library</td>\n<td>Telnet</td>\n<td>telnetlib_log_level=NONE</td>\n<td></td>\n<td></td>\n<td># disable logging messages from the underlying telnetlib</td>\n</tr>\n</table>',
      shortdoc:
        "Telnet library can be imported with optional configuration parameters.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 281,
    },
  ],
  keywords: [
    {
      name: "Close All Connections",
      args: [],
      returnType: null,
      doc: '<p>Closes all open connections and empties the connection cache.</p>\n<p>If multiple connections are opened, this keyword should be used in a test or suite teardown to make sure that all connections are closed. It is not an error if some of the connections have already been closed by <a href="#Close%20Connection" class="name">Close Connection</a>.</p>\n<p>After this keyword, new indexes returned by <a href="#Open%20Connection" class="name">Open Connection</a> keyword are reset to 1.</p>',
      shortdoc: "Closes all open connections and empties the connection cache.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 470,
    },
    {
      name: "Close Connection",
      args: [
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
      ],
      returnType: null,
      doc: '<p>Closes the current Telnet connection.</p>\n<p>Remaining output in the connection is read, logged, and returned. It is not an error to close an already closed connection.</p>\n<p>Use <a href="#Close%20All%20Connections" class="name">Close All Connections</a> if you want to make sure all opened connections are closed.</p>\n<p>See <a href="#Logging" class="name">Logging</a> section for more information about log levels.</p>',
      shortdoc: "Closes the current Telnet connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 686,
    },
    {
      name: "Execute Command",
      args: [
        {
          name: "command",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "command",
        },
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
        {
          name: "strip_prompt",
          type: null,
          defaultValue: "False",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "strip_prompt=False",
        },
      ],
      returnType: null,
      doc: '<p>Executes the given <code>command</code> and reads, logs, and returns everything until the prompt.</p>\n<p>This keyword requires the prompt to be <a href="#Configuration">configured</a> either in <a href="#Importing" class="name">importing</a> or with <a href="#Open%20Connection" class="name">Open Connection</a> or <a href="#Set%20Prompt" class="name">Set Prompt</a> keyword.</p>\n<p>This is a convenience keyword that uses <a href="#Write" class="name">Write</a> and <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a> internally. Following two examples are thus functionally identical:</p>\n<table border="1">\n<tr>\n<td>${out} =</td>\n<td><a href="#Execute%20Command" class="name">Execute Command</a></td>\n<td>pwd</td>\n</tr>\n</table>\n<table border="1">\n<tr>\n<td><a href="#Write" class="name">Write</a></td>\n<td>pwd</td>\n</tr>\n<tr>\n<td>${out} =</td>\n<td><a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a></td>\n</tr>\n</table>\n<p>See <a href="#Logging" class="name">Logging</a> section for more information about log levels and <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a> for more information about the <code>strip_prompt</code> parameter.</p>',
      shortdoc:
        "Executes the given ``command`` and reads, logs, and returns everything until the prompt.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 1054,
    },
    {
      name: "Login",
      args: [
        {
          name: "username",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "username",
        },
        {
          name: "password",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "password",
        },
        {
          name: "login_prompt",
          type: null,
          defaultValue: "login: \\",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "login_prompt=login: \\",
        },
        {
          name: "password_prompt",
          type: null,
          defaultValue: "Password: \\",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "password_prompt=Password: \\",
        },
        {
          name: "login_timeout",
          type: null,
          defaultValue: "1 second",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "login_timeout=1 second",
        },
        {
          name: "login_incorrect",
          type: null,
          defaultValue: "Login incorrect",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "login_incorrect=Login incorrect",
        },
      ],
      returnType: null,
      doc: '<p>Logs in to the Telnet server with the given user information.</p>\n<p>This keyword reads from the connection until the <code>login_prompt</code> is encountered and then types the given <code>username</code>. Then it reads until the <code>password_prompt</code> and types the given <code>password</code>. In both cases a newline is appended automatically and the connection specific timeout used when waiting for outputs.</p>\n<p>How logging status is verified depends on whether a prompt is set for this connection or not:</p>\n<p>1) If the prompt is set, this keyword reads the output until the prompt is found using the normal timeout. If no prompt is found, login is considered failed and also this keyword fails. Note that in this case both <code>login_timeout</code> and <code>login_incorrect</code> arguments are ignored.</p>\n<p>2) If the prompt is not set, this keywords sleeps until <code>login_timeout</code> and then reads all the output available on the connection. If the output contains <code>login_incorrect</code> text, login is considered failed and also this keyword fails.</p>\n<p>See <a href="#Configuration" class="name">Configuration</a> section for more information about setting newline, timeout, and prompt.</p>',
      shortdoc: "Logs in to the Telnet server with the given user information.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 704,
    },
    {
      name: "Open Connection",
      args: [
        {
          name: "host",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "host",
        },
        {
          name: "alias",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "alias=None",
        },
        {
          name: "port",
          type: null,
          defaultValue: "23",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "port=23",
        },
        {
          name: "timeout",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "timeout=None",
        },
        {
          name: "newline",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "newline=None",
        },
        {
          name: "prompt",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "prompt=None",
        },
        {
          name: "prompt_is_regexp",
          type: null,
          defaultValue: "False",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "prompt_is_regexp=False",
        },
        {
          name: "encoding",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "encoding=None",
        },
        {
          name: "encoding_errors",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "encoding_errors=None",
        },
        {
          name: "default_log_level",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "default_log_level=None",
        },
        {
          name: "window_size",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "window_size=None",
        },
        {
          name: "environ_user",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "environ_user=None",
        },
        {
          name: "terminal_emulation",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "terminal_emulation=None",
        },
        {
          name: "terminal_type",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "terminal_type=None",
        },
        {
          name: "telnetlib_log_level",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "telnetlib_log_level=None",
        },
        {
          name: "connection_timeout",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "connection_timeout=None",
        },
      ],
      returnType: null,
      doc: '<p>Opens a new Telnet connection to the given host and port.</p>\n<p>The <code>timeout</code>, <code>newline</code>, <code>prompt</code>, <code>prompt_is_regexp</code>, <code>encoding</code>, <code>default_log_level</code>, <code>window_size</code>, <code>environ_user</code>, <code>terminal_emulation</code>, <code>terminal_type</code> and <code>telnetlib_log_level</code> arguments get default values when the library is <a href="#Importing">imported</a>. Setting them here overrides those values for the opened connection. See <a href="#Configuration" class="name">Configuration</a>, <a href="#Terminal%20emulation" class="name">Terminal emulation</a> and <a href="#Logging" class="name">Logging</a> sections for more information about these parameters and their possible values.</p>\n<p>Possible already opened connections are cached and it is possible to switch back to them using <a href="#Switch%20Connection" class="name">Switch Connection</a> keyword. It is possible to switch either using explicitly given <code>alias</code> or using index returned by this keyword. Indexing starts from 1 and is reset back to it by <a href="#Close%20All%20Connections" class="name">Close All Connections</a> keyword.</p>',
      shortdoc: "Opens a new Telnet connection to the given host and port.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 362,
    },
    {
      name: "Read",
      args: [
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
      ],
      returnType: null,
      doc: '<p>Reads everything that is currently available in the output.</p>\n<p>Read output is both returned and logged. See <a href="#Logging" class="name">Logging</a> section for more information about log levels.</p>',
      shortdoc: "Reads everything that is currently available in the output.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 874,
    },
    {
      name: "Read Until",
      args: [
        {
          name: "expected",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "expected",
        },
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
      ],
      returnType: null,
      doc: '<p>Reads output until <code>expected</code> text is encountered.</p>\n<p>Text up to and including the match is returned and logged. If no match is found, this keyword fails. How much to wait for the output depends on the <a href="#Configuration">configured timeout</a>.</p>\n<p>See <a href="#Logging" class="name">Logging</a> section for more information about log levels. Use <a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a> if more complex matching is needed.</p>',
      shortdoc: "Reads output until ``expected`` text is encountered.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 888,
    },
    {
      name: "Read Until Prompt",
      args: [
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
        {
          name: "strip_prompt",
          type: null,
          defaultValue: "False",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "strip_prompt=False",
        },
      ],
      returnType: null,
      doc: '<p>Reads output until the prompt is encountered.</p>\n<p>This keyword requires the prompt to be <a href="#Configuration">configured</a> either in <a href="#Importing" class="name">importing</a> or with <a href="#Open%20Connection" class="name">Open Connection</a> or <a href="#Set%20Prompt" class="name">Set Prompt</a> keyword.</p>\n<p>By default, text up to and including the prompt is returned and logged. If no prompt is found, this keyword fails. How much to wait for the output depends on the <a href="#Configuration">configured timeout</a>.</p>\n<p>If you want to exclude the prompt from the returned output, set <code>strip_prompt</code> to a true value (see <a href="#Boolean%20arguments" class="name">Boolean arguments</a>). If your prompt is a regular expression, make sure that the expression spans the whole prompt, because only the part of the output that matches the regular expression is stripped away.</p>\n<p>See <a href="#Logging" class="name">Logging</a> section for more information about log levels.</p>',
      shortdoc: "Reads output until the prompt is encountered.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 1009,
    },
    {
      name: "Read Until Regexp",
      args: [
        {
          name: "expected",
          type: null,
          defaultValue: null,
          kind: "VAR_POSITIONAL",
          required: false,
          repr: "*expected",
        },
      ],
      returnType: null,
      doc: '<p>Reads output until any of the <code>expected</code> regular expressions match.</p>\n<p>This keyword accepts any number of regular expressions patterns or compiled Python regular expression objects as arguments. Text up to and including the first match to any of the regular expressions is returned and logged. If no match is found, this keyword fails. How much to wait for the output depends on the <a href="#Configuration">configured timeout</a>.</p>\n<p>If the last given argument is a <a href="#Logging">valid log level</a>, it is used as <code>loglevel</code> similarly as with <a href="#Read%20Until" class="name">Read Until</a> keyword.</p>\n<p>See the documentation of <a href="http://docs.python.org/library/re.html">Python re module</a> for more information about the supported regular expression syntax. Notice that possible backslashes need to be escaped in Robot Framework data.</p>\n<p>Examples:</p>\n<table border="1">\n<tr>\n<td><a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a></td>\n<td>(#|$)</td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a></td>\n<td>first_regexp</td>\n<td>second_regexp</td>\n</tr>\n<tr>\n<td><a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a></td>\n<td>\\\\d{4}-\\\\d{2}-\\\\d{2}</td>\n<td>DEBUG</td>\n</tr>\n</table>',
      shortdoc:
        "Reads output until any of the ``expected`` regular expressions match.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 972,
    },
    {
      name: "Set Default Log Level",
      args: [
        {
          name: "level",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "level",
        },
      ],
      returnType: null,
      doc: '<p>Sets the default log level used for <a href="#Logging" class="name">logging</a> in the current connection.</p>\n<p>The old default log level is returned and can be used to restore the log level later.</p>\n<p>See <a href="#Configuration" class="name">Configuration</a> section for more information about global and connection specific configuration.</p>',
      shortdoc:
        "Sets the default log level used for `logging` in the current connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 660,
    },
    {
      name: "Set Encoding",
      args: [
        {
          name: "encoding",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "encoding=None",
        },
        {
          name: "errors",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "errors=None",
        },
      ],
      returnType: null,
      doc: '<p>Sets the encoding to use for <a href="#Writing%20and%20reading" class="name">writing and reading</a> in the current connection.</p>\n<p>The given <code>encoding</code> specifies the encoding to use when written/read text is encoded/decoded, and <code>errors</code> specifies the error handler to use if encoding/decoding fails. Either of these can be omitted and in that case the old value is not affected. Use string <code>NONE</code> to disable encoding altogether.</p>\n<p>See <a href="#Configuration" class="name">Configuration</a> section for more information about encoding and error handlers, as well as global and connection specific configuration in general.</p>\n<p>The old values are returned and can be used to restore the encoding and the error handler later. See <a href="#Set%20Prompt" class="name">Set Prompt</a> for a similar example.</p>\n<p>If terminal emulation is used, the encoding can not be changed on an open connection.</p>',
      shortdoc:
        "Sets the encoding to use for `writing and reading` in the current connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 601,
    },
    {
      name: "Set Newline",
      args: [
        {
          name: "newline",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "newline",
        },
      ],
      returnType: null,
      doc: '<p>Sets the newline used by <a href="#Write" class="name">Write</a> keyword in the current connection.</p>\n<p>The old newline is returned and can be used to restore the newline later. See <a href="#Set%20Timeout" class="name">Set Timeout</a> for a similar example.</p>\n<p>If terminal emulation is used, the newline can not be changed on an open connection.</p>\n<p>See <a href="#Configuration" class="name">Configuration</a> section for more information about global and connection specific configuration.</p>',
      shortdoc:
        "Sets the newline used by `Write` keyword in the current connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 540,
    },
    {
      name: "Set Prompt",
      args: [
        {
          name: "prompt",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "prompt",
        },
        {
          name: "prompt_is_regexp",
          type: null,
          defaultValue: "False",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "prompt_is_regexp=False",
        },
      ],
      returnType: null,
      doc: '<p>Sets the prompt used by <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a> and <a href="#Login" class="name">Login</a> in the current connection.</p>\n<p>If <code>prompt_is_regexp</code> is given a true value (see <a href="#Boolean%20arguments" class="name">Boolean arguments</a>), the given <code>prompt</code> is considered to be a regular expression.</p>\n<p>The old prompt is returned and can be used to restore the prompt later.</p>\n<p>Example:</p>\n<table border="1">\n<tr>\n<td>${prompt}</td>\n<td>${regexp} =</td>\n<td><a href="#Set%20Prompt" class="name">Set Prompt</a></td>\n<td>$</td>\n</tr>\n<tr>\n<td><span class="name">Do Something</span></td>\n<td></td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Set%20Prompt" class="name">Set Prompt</a></td>\n<td>${prompt}</td>\n<td>${regexp}</td>\n<td></td>\n</tr>\n</table>\n<p>See the documentation of <a href="http://docs.python.org/library/re.html">Python re module</a> for more information about the supported regular expression syntax. Notice that possible backslashes need to be escaped in Robot Framework data.</p>\n<p>See <a href="#Configuration" class="name">Configuration</a> section for more information about global and connection specific configuration.</p>',
      shortdoc:
        "Sets the prompt used by `Read Until Prompt` and `Login` in the current connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 563,
    },
    {
      name: "Set Telnetlib Log Level",
      args: [
        {
          name: "level",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "level",
        },
      ],
      returnType: null,
      doc: '<p>Sets the log level used for <a href="#Logging" class="name">logging</a> in the underlying <code>telnetlib</code>.</p>\n<p>Note that <code>telnetlib</code> can be very noisy thus using the level <code>NONE</code> can shutdown the messages generated by this library.</p>',
      shortdoc:
        "Sets the log level used for `logging` in the underlying ``telnetlib``.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 642,
    },
    {
      name: "Set Timeout",
      args: [
        {
          name: "timeout",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "timeout",
        },
      ],
      returnType: null,
      doc: '<p>Sets the timeout used for waiting output in the current connection.</p>\n<p>Read operations that expect some output to appear (<a href="#Read%20Until" class="name">Read Until</a>, <a href="#Read%20Until%20Regexp" class="name">Read Until Regexp</a>, <a href="#Read%20Until%20Prompt" class="name">Read Until Prompt</a>, <a href="#Login" class="name">Login</a>) use this timeout and fail if the expected output does not appear before this timeout expires.</p>\n<p>The <code>timeout</code> must be given in <a href="#Time%20string%20format" class="name">time string format</a>. The old timeout is returned and can be used to restore the timeout later.</p>\n<p>Example:</p>\n<table border="1">\n<tr>\n<td>${old} =</td>\n<td><a href="#Set%20Timeout" class="name">Set Timeout</a></td>\n<td>2 minute 30 seconds</td>\n</tr>\n<tr>\n<td><span class="name">Do Something</span></td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Set%20Timeout" class="name">Set Timeout</a></td>\n<td>${old}</td>\n<td></td>\n</tr>\n</table>\n<p>See <a href="#Configuration" class="name">Configuration</a> section for more information about global and connection specific configuration.</p>',
      shortdoc:
        "Sets the timeout used for waiting output in the current connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 514,
    },
    {
      name: "Switch Connection",
      args: [
        {
          name: "index_or_alias",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "index_or_alias",
        },
      ],
      returnType: null,
      doc: '<p>Switches between active connections using an index or an alias.</p>\n<p>Aliases can be given to <a href="#Open%20Connection" class="name">Open Connection</a> keyword which also always returns the connection index.</p>\n<p>This keyword returns the index of previous active connection.</p>\n<p>Example:</p>\n<table border="1">\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>myhost.net</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Login" class="name">Login</a></td>\n<td>john</td>\n<td>secret</td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Write" class="name">Write</a></td>\n<td>some command</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>yourhost.com</td>\n<td>2nd conn</td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Login" class="name">Login</a></td>\n<td>root</td>\n<td>password</td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Write" class="name">Write</a></td>\n<td>another cmd</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td>${old index}=</td>\n<td><a href="#Switch%20Connection" class="name">Switch Connection</a></td>\n<td>1</td>\n<td># index</td>\n</tr>\n<tr>\n<td><a href="#Write" class="name">Write</a></td>\n<td>something</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Switch%20Connection" class="name">Switch Connection</a></td>\n<td>2nd conn</td>\n<td></td>\n<td># alias</td>\n</tr>\n<tr>\n<td><a href="#Write" class="name">Write</a></td>\n<td>whatever</td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Switch%20Connection" class="name">Switch Connection</a></td>\n<td>${old index}</td>\n<td></td>\n<td># back to original</td>\n</tr>\n<tr>\n<td>[Teardown]</td>\n<td><a href="#Close%20All%20Connections" class="name">Close All Connections</a></td>\n<td></td>\n<td></td>\n</tr>\n</table>\n<p>The example above expects that there were no other open connections when opening the first one, because it used index <code>1</code> when switching to the connection later. If you are not sure about that, you can store the index into a variable as shown below.</p>\n<table border="1">\n<tr>\n<td>${index} =</td>\n<td><a href="#Open%20Connection" class="name">Open Connection</a></td>\n<td>myhost.net</td>\n</tr>\n<tr>\n<td><span class="name">Do Something</span></td>\n<td></td>\n<td></td>\n</tr>\n<tr>\n<td><a href="#Switch%20Connection" class="name">Switch Connection</a></td>\n<td>${index}</td>\n<td></td>\n</tr>\n</table>',
      shortdoc:
        "Switches between active connections using an index or an alias.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 434,
    },
    {
      name: "Write",
      args: [
        {
          name: "text",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "text",
        },
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
      ],
      returnType: null,
      doc: '<p>Writes the given text plus a newline into the connection.</p>\n<p>The newline character sequence to use can be <a href="#Configuration">configured</a> both globally and per connection basis. The default value is <code>CRLF</code>.</p>\n<p>This keyword consumes the written text, until the added newline, from the output and logs and returns it. The given text itself must not contain newlines. Use <a href="#Write%20Bare" class="name">Write Bare</a> instead if either of these features causes a problem.</p>\n<p><b>Note:</b> This keyword does not return the possible output of the executed command. To get the output, one of the <span class="name">Read ...</span> <a href="#Keywords" class="name">keywords</a> must be used. See <a href="#Writing%20and%20reading" class="name">Writing and reading</a> section for more details.</p>\n<p>See <a href="#Logging" class="name">Logging</a> section for more information about log levels.</p>',
      shortdoc: "Writes the given text plus a newline into the connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 759,
    },
    {
      name: "Write Bare",
      args: [
        {
          name: "text",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "text",
        },
      ],
      returnType: null,
      doc: '<p>Writes the given text, and nothing else, into the connection.</p>\n<p>This keyword does not append a newline nor consume the written text. Use <a href="#Write" class="name">Write</a> if these features are needed.</p>',
      shortdoc: "Writes the given text, and nothing else, into the connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 789,
    },
    {
      name: "Write Control Character",
      args: [
        {
          name: "character",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "character",
        },
      ],
      returnType: null,
      doc: '<p>Writes the given control character into the connection.</p>\n<p>The control character is prepended with an IAC (interpret as command) character.</p>\n<p>The following control character names are supported: BRK, IP, AO, AYT, EC, EL, NOP. Additionally, you can use arbitrary numbers to send any control character.</p>\n<p>Example:</p>\n<table border="1">\n<tr>\n<td>Write Control Character</td>\n<td>BRK</td>\n<td># Send Break command</td>\n</tr>\n<tr>\n<td>Write Control Character</td>\n<td>241</td>\n<td># Send No operation command</td>\n</tr>\n</table>',
      shortdoc: "Writes the given control character into the connection.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 835,
    },
    {
      name: "Write Until Expected Output",
      args: [
        {
          name: "text",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "text",
        },
        {
          name: "expected",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "expected",
        },
        {
          name: "timeout",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "timeout",
        },
        {
          name: "retry_interval",
          type: null,
          defaultValue: null,
          kind: "POSITIONAL_OR_NAMED",
          required: true,
          repr: "retry_interval",
        },
        {
          name: "loglevel",
          type: null,
          defaultValue: "None",
          kind: "POSITIONAL_OR_NAMED",
          required: false,
          repr: "loglevel=None",
        },
      ],
      returnType: null,
      doc: '<p>Writes the given <code>text</code> repeatedly, until <code>expected</code> appears in the output.</p>\n<p><code>text</code> is written without appending a newline and it is consumed from the output before trying to find <code>expected</code>. If <code>expected</code> does not appear in the output within <code>timeout</code>, this keyword fails.</p>\n<p><code>retry_interval</code> defines the time to wait <code>expected</code> to appear before writing the <code>text</code> again. Consuming the written <code>text</code> is subject to the normal <a href="#Configuration">configured timeout</a>.</p>\n<p>Both <code>timeout</code> and <code>retry_interval</code> must be given in <a href="#Time%20string%20format" class="name">time string format</a>. See <a href="#Logging" class="name">Logging</a> section for more information about log levels.</p>\n<p>Example:</p>\n<table border="1">\n<tr>\n<td>Write Until Expected Output</td>\n<td>ps -ef| grep myprocess\\r\\n</td>\n<td>myprocess</td>\n</tr>\n<tr>\n<td>...</td>\n<td>5 s</td>\n<td>0.5 s</td>\n</tr>\n</table>\n<p>The above example writes command <code>ps -ef | grep myprocess\\r\\n</code> until <code>myprocess</code> appears in the output. The command is written every 0.5 seconds and the keyword fails if <code>myprocess</code> does not appear in the output in 5 seconds.</p>',
      shortdoc:
        "Writes the given ``text`` repeatedly, until ``expected`` appears in the output.",
      tags: [],
      source: "/Users/jth/Code/robotframework/src/robot/libraries/Telnet.py",
      lineno: 798,
    },
  ],
  typedocs: [],
};

export { Libdoc, DATA };
